// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220407062155_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Australia",
                            ShortName = "AU"
                        },
                        new
                        {
                            Id = 2,
                            Name = "New Zealand",
                            ShortName = "NZ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Great Britain",
                            ShortName = "UK"
                        });
                });

            modelBuilder.Entity("api.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Address = "42 Russell St Melbourne",
                            CountryId = 1,
                            Name = "Royal Plaza",
                            Rating = "5"
                        },
                        new
                        {
                            Id = 1,
                            Address = "101 Lonsdale St Melbourne",
                            CountryId = 1,
                            Name = "The Big Hotel",
                            Rating = "4"
                        },
                        new
                        {
                            Id = 2,
                            Address = "55 Smith Rd Cantebury",
                            CountryId = 2,
                            Name = "Kiwi Place",
                            Rating = "5"
                        },
                        new
                        {
                            Id = 3,
                            Address = "450 London Bvld London",
                            CountryId = 3,
                            Name = "The Royal Oak",
                            Rating = "3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1000 Bridge Rd Newcastle",
                            CountryId = 1,
                            Name = "Covid Place",
                            Rating = "4.4"
                        });
                });

            modelBuilder.Entity("api.Data.Hotel", b =>
                {
                    b.HasOne("api.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
